INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Toys ''R'' Us', '#02-183', '10am-10pm','http://www.toysrus.com.sg/', '67330190', 'Toys"R"Us is positioned as "the Worldwide authority on kids, families and fun". It is the largest child-related product specialty chain store in the world. Toys"R"Us believes in providing a happy shopping experience to customers with the biggest selection of toys and baby products priced to offer best value for money.', 'http://localhost:8080/Stores/toysAreUs.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Boost Juice', '#02-134','10am-10pm','http://www.boostjuicebars.com.sg/', '63769300', 'Australia''s #1 Juice & Smoothie bar is here in Singapore! Boost offers a healthy alternative to fast food. Their menu offers real fruit juices, crushes and delicious low-fat smoothies made with top secret TD4 (To Die For) low-fat frozen yogurt. All products are at least 98% fat-free and we never ever add artificial flavours, colours, sugar or water.', 'http://localhost:8080/Stores/boostJuice.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Challenger', '#02-34', '10am-10pm', 'https://www.challenger.com.sg/', '63766100', 'Challenger is a dynamic regional IT retailer known for its strong brand name and attractive ValueClub membership privileges. They deliver every day value to their members on the latest IT gadgets and lifestyle products.', 'http://localhost:8080/Stores/challenger.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Dental on the Bay', '#02-230', '10am-10pm', 'http://www.dentalonthebay.com/', '63769001', 'Your smile, your life, their passion. At Dental On The Bay, they are dedicated to providing you with quality dental care and services. Equipped with state-of-the-art technology, and comprehensive personalized service, you can be assured of remarkable results with a gently touch.', 'http://localhost:8080/Stores/dentalByTheBay.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Factorie', '#02-48', '10am-10pm', 'http://www.factorie.com.au/', '63769217', 'Factorie is as much a statement about youth as it is a lifestyle destination for casual, on-trend guys and girls fashion. Established in 2007 and growing internationally to over 200 stores across Australia, New Zealand, South Africa, Singapore, Malaysia and the Philippines, Factorie is everything you’d expect from a brand that loves a carefree lifestyle of friends, fashion, social updates and more – taking inspiration from the street, to the beach and everything in-between.', 'http://localhost:8080/Stores/factorie.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('G2000', '#02-239', '10am-10pm', 'http://www.g2000.com.sg/', '63769946', 'G2000 is the savvy executive’s choice that takes business to a personal level, providing easy-to-wear trends and updated classics with an Asian fit. Flaunt your individual style with a versatile range of work wear and smart essentials that offers a balance of tailored elegance and sharp style, taking you from 9 to 5 and beyond.', 'http://localhost:8080/Stores/G2000.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Golden Village', '#02-30', '10am-10pm', 'https://www.gv.com.sg/', '66538100', 'Golden Village Multiplex opened GV VivoCity, its ninth flagship and the largest cinema complex in Singapore on 7 October 2006. GV VivoCity houses GVmax - the ultimate big screen experience in a gigantic, stadium-like auditorium with 602 seats and one of the widest screens in Asia, 3 Gold Class cinemas and 11 new stadium cinemas. In November 2012, Golden Village, together with Dolby Laboratories launched Dolby’s latest new cinema sound format, Dolby® Atmos™, at its largest cinema hall, GVmax®. Golden Village’s GVmax® radial stadium seating, with one of its widest cinema screen in Asia is now accompanied by a crystal-clear 4K digital projection.', 'http://localhost:8080/Stores/goldenVillage.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Lego', '#02-90', '10am-10pm', 'https://www.lego.com/en-sg/', '64659230', 'The LEGO Group is a privately held, family-owned company with headquarters in Billund, Denmark, and main offices in Enfield, USA, London, UK, Shanghai, China, and Singapore. Founded in 1932 by Ole Kirk Kristiansen, and based on the iconic LEGO® brick, it is one of the world''s leading manufacturers of play materials. Guided by the company spirit: "Only the best is good enough”, the company is committed to the development of children and aims to inspire and develop the builders of tomorrow through creative play and learning. LEGO products are sold worldwide and can be virtually explored at www.LEGO.com', 'http://localhost:8080/Stores/lego.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Long John Silver''s', '#02-94', '8am-10pm', 'http://www.longjohnsilvers.com.sg/', '63769452', 'In Singapore, the first Long John Silver’s restaurant was opened in 1983 in response to the growing consumer demand for quick service restaurants. Their secret batter prepared fresh throughout the day makes Long John Silver’s seafood tastes like no other seafood in the world. Enjoy the burst of flavours in your mouth, with each bite of their signature crunchy batter-dipped indulgence. Whether you are looking for great fish, seafood and chicken at an affordable price, or a perfect place to dine with your family and friends, Long John Silver''s has something for everyone.' , 'http://localhost:8080/Stores/longJohnSilvers.png');

INSERT INTO stores (name, unit, opening, website, number, description, diagram)
VALUES('Rip Curl', '#02-26', '10am-10pm', 'https://www.ripcurl.asia/en/', '62752680', 'Rip Curl is a major Australian designer, manufacturer, and retailer who specializes in surfing sportswear, wetsuits and accompanying products.', 'http://localhost:8080/Stores/ripCurl.png');